# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83b44c2def5f53868f86d1a6e3999e338ffa3223ce8622e057c97d16bc0f453fb83192bd6d939018bb7a30b244574de1522e46d1510ecbc0856f6cff20da5a8f

test:
  secret_key_base: bce7eb334c60168875bcbb7f27dfa8c399d8fd0976c78c10201850fa263068094ad0b4200b1eac28e6c12804625e2e1c299b0f789245791f69bcd7f93a8f8d8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
